config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # config = ActiveAdmin::Devise.config
  # config[:controllers][:sessions] = "users/sessions"
  # config[:controllers][:registrations] = "devise/registrations"
  # devise_for :users, config

  devise_for :users,
             path:        "auth",
             controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root to: "main#index"

  get "/about", to: "about#index"

  get "/items/search", to: "items#search"
  resources :items, only: %i[index show]

  post "/categories/filter/:id", to: "categories#search"
  delete "/categories/destroy_picks", to: "categories#destroy_picks"
  resources :categories, only: %i[index show]

  post "/cart/buy", to: "cart#buy"
  post "/cart/add/qty/:id", to: "cart#add"
  post "/cart/subtract/qty/:id", to: "cart#subtract"
  resources :cart, only: %i[index create destroy]

  get "/order/review", to: "orders#review"
  resources :orders, only: %i[index create show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @order_sub = []
    @carts = if session[:shopping_cart].count.positive?
               Item.find(session[:shopping_cart].map { |item| item["id"] })
             else
               []
             end

    if @carts.count.positive? || @carts != []
      @qty_array = session[:shopping_cart].map { |item| item["qty"].to_i }

      @order_sub = (@carts.map.with_index { |item, index| item.price * @qty_array[index].to_i })
      if current_user
        @order_taxes = @order_sub.sum * (current_user.province.gst + current_user.province.pst)
      end
      @order_total = @order_sub.sum + @order_taxes if current_user
    end

    render "cart/index" and return
  end

  # POST /cart
  def create
    item = Item.find(params[:id])
    logger.debug("Adding #{item.title} to cart.")

    session[:shopping_cart] << { id: item.id, qty: 1 }

    flash[:notice] = "#{item.title} added to cart!"
    redirect_back(fallback_location: root_path)
  end

  # DELETE /cart/:id
  def destroy
    session[:shopping_cart].delete_if { |item| item["id"].to_i == params[:id].to_i }

    session[:shopping_cart] = [] if session[:shopping_cart].count == 0
    flash[:notice] = " #{Item.find(params[:id]).title} removed from cart."
    redirect_back(fallback_location: root_path)
  end

  # POST /cart/buy/:id
  def buy
    id = params[:id].to_i
    title = params[:title].to_s
    session[:shopping_cart] << id

    flash[:notice] = "#{title} added to cart!"
    redirect_to cart_index_path
  end

  def add
    session[:shopping_cart].each do |item|
      item["qty"] += 1 if item["id"].to_i == params[:id].to_i
    end
    redirect_back(fallback_location: root_path)
  end

  def subtract
    session[:shopping_cart].each do |item|
      next unless item["id"].to_i == params[:id].to_i

      item["qty"] -= 1
      session[:shopping_cart].delete(item) if item["qty"] < 1
    end
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<div class="cart-item">
  <% if cart.picture.present? %>
      <p><%= image_tag cart.picture.variant(resize_to_limit: [250, 250]).processed, alt: "#{cart.title}"  %></p>
  <% end %>

  <div class="d-flex ms-3">
    <hr/>
    <h5><%= cart.title %></h5>
    <div class="d-flex mb-3">
      <%= button_to "/cart/subtract/qty/#{cart.id}", method: :post, class: "btn btn-primary" do %>
        <i class="bi bi-dash-lg"></i>
      <% end %>
      <%= text_field_tag :price, "#{session[:shopping_cart].select {|i| i["id"]==cart.id}[0]["qty"]}", disabled: true, class: "ms-2 me-2" %>
      <%= button_to "/cart/add/qty/#{cart.id}", method: :post, class: "btn btn-primary" do %>
        <i class="bi bi-plus-lg"></i>
      <% end %>
    </div>
    <%= link_to "Remove From Cart", cart_path(cart), method: :delete, class: "btn btn-danger" %>
  </div>

  <p class="price">Price: <%= number_to_currency (cart.price*@qty_array[cart_counter]) / 1.0 %></p>
</div>
<br />

app/views/cart/_cart_buy.html.erb
<div id="cart-summary">
  <h3><strong>Order Summary</strong></h3>
  <div class="table-responsive">
    <table class="table table-striped">
      <tbody>
        <tr>
          <th>Order Subtotal</th>
          <td><%= number_to_currency @order_sub.count.positive? ? (@order_sub.sum / 1.0) : 0  %></td>
        </tr>
        <tr>
          <th>Shipping Costs</th>
          <td>Free</td>
        </tr>
        <% if current_user and @order_sub != [] %>
          <tr>
            <th>Estimated Taxes</th>
            <td><%= number_to_currency (@order_taxes) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table class="table">
      <tbody>
        <tr>
          <th><strong>Estimated Total</strong></th>
          <td><strong><%= number_to_currency (current_user and @order_sub.count.positive? ? @order_total : @order_sub.sum) %></strong></td>
        </tr>
      </tbody>
    </table>
  </div>
  <% if current_user and @order_sub.count.positive? %>
    <%= link_to("Proceed to Checkout", order_review_path, class: "btn btn-warning d-inline-block w-100") %>
  <% else %>
    <%= button_to("Proceed to Checkout", order_review_path, disabled: true, class: "btn btn-warning d-inline-block w-100") %>
  <% end %>
  <%= link_to_if(current_user.nil?, "Login", { controller: "users/sessions", action: "create" }, class: "btn btn-primary d-inline-block w-100 mt-2") do
    ""
  end %>
</div>

app/views/cart/index.html.erb
<div id="carts" class="container mb-5" style="display:flex;">
  <div class="col-7">
    <%= render partial: "cart", collection: @carts %>
  </div>
  <div class="col-4">
    <%= render partial: "cart_buy" %>
  </div>
</div>