config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # config = ActiveAdmin::Devise.config
  # config[:controllers][:sessions] = "users/sessions"
  # config[:controllers][:registrations] = "devise/registrations"
  # devise_for :users, config

  devise_for :users,
             path:        "auth",
             controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root to: "main#index"

  get "/about", to: "about#index"

  get "/items/search", to: "items#search"
  resources :items, only: %i[index show]

  post "/categories/filter/:id", to: "categories#search"
  delete "/categories/destroy_picks", to: "categories#destroy_picks"
  resources :categories, only: %i[index show]

  post "/cart/buy", to: "cart#buy"
  post "/cart/add/qty/:id", to: "cart#add"
  post "/cart/subtract/qty/:id", to: "cart#subtract"
  resources :cart, only: %i[index create destroy]

  get "/order/review", to: "orders#review"
  resources :orders, only: %i[index create show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="bg-secondary text-white pt-5 pb-5">
  <div class="container">
    <div class="row">
      <div class="col">
        KeyStrings
      </div>
      <div class="col">
        Reviews
      </div>
      <div class="col">
        Help
        <div class="row ms-2">
          <div class="row">FAQs</div>
          <div class="row">Guide to Custom Keyboards</div>
          <div class="row">Call your nearest store</div>
          <div class="row"></div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <div class="d-flex">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "KeyStrings", root_path, class: "navbar-brand", style: "font-size:30px;margin-left:10px;" %>
      </div>

      <div>
      <%= form_tag(items_search_path, method: "get", class: "d-flex", style: "width:auto;position:relative;") do %>

        <%= search_field_tag :search, params[:search], placeholder: "Search Items", value: "#{session[:search]}", class: "form-control me-2"%>

        <%= button_tag "Search", class: "btn btn-outline-success"%>
        <%= link_to cart_index_path, style: "display:flex;" do %>
            <i class="bi bi-cart2" style="font-size:30px;margin-left:5px;padding-right:5px;"></i>
          <% if cart.present? %>
            <sup style="font-size:20px;position:absolute;right:0px;top:3px;"><%= cart.size %></sup>
          <% end %>
        <% end %>
      <% end %>
        <%# <form class="d-flex" action="/items/search" method="get">
          <input class="form-control me-2" type="search" placeholder="Search Items" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
          <a href="/about"><i class="bi bi-cart2" style="font-size:30px;margin-left:5px;"></i></a>
        </form> %>
      </div>

      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <a class="nav-link offcanvas-title navbar-brand" id="offcanvasNavbarLabel" aria-current="page" href="/">KeyStrings</a>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <% if (user_signed_in?) %>
              <li class="nav-item">
                <%= link_to"Account", edit_user_registration_path(@user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Orders",  orders_path, class: "nav-link" %>
              </li>
            <% end %>

            <li class="nav-item">
              <%= link_to cart_index_path, class: "nav-link" do %>
                Cart
                <% if cart.present? %>
                  <sup><%= cart.size %></sup>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Shop
              </a>
              <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                <li>
                  <%= link_to "Browse Categories", categories_path, class: "dropdown-item" %>
                </li>
                <li><a class="dropdown-item" href="#">Order Custom Keyboards</a></li>
              </ul>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About Us</a>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>