config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # config = ActiveAdmin::Devise.config
  # config[:controllers][:sessions] = "users/sessions"
  # config[:controllers][:registrations] = "devise/registrations"
  # devise_for :users, config

  devise_for :users,
             path:        "auth",
             controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root to: "main#index"

  get "/about", to: "about#index"

  get "/items/search", to: "items#search"
  resources :items, only: %i[index show]

  post "/categories/filter/:id", to: "categories#search"
  delete "/categories/destroy_picks", to: "categories#destroy_picks"
  resources :categories, only: %i[index show]

  post "/cart/buy", to: "cart#buy"
  post "/cart/add/qty/:id", to: "cart#add"
  post "/cart/subtract/qty/:id", to: "cart#subtract"
  resources :cart, only: %i[index create destroy]

  get "/order/review", to: "orders#review"
  resources :orders, only: %i[index create show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many   :order_histories

  has_one_attached :picture do |attachable|
    attachable.variant :thumb, resize: "100x100"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def search
    if params[:search].blank?
      session[:search] = nil
      redirect_to root_path and return
    else
      session[:search] = params[:search].downcase
      redirect_to categories_path and return
    end

    # if params[:search].blank?
    #   redirect_to root_path and return
    # else
    #   @parameter = params[:search].downcase
    #   @items = Item.all.where("lower(title) LIKE :search",
    #                           search: "%#{@parameter}%").page(params[:page])
    # end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<aside>
  <% if item.picture.present? %>
    <% if (params[:action] == 'index' || params[:action] == 'search') %>
      <p><%= image_tag item.picture.variant(resize_to_limit: [285, 285]).processed, alt: "#{item.title}"  %></p>
    <% else %>
      <p><%= image_tag item.picture.variant(resize_to_limit: [600, 600]).processed, alt: "#{item.title}"  %></p>
    <% end %>
  <% end %>
  <% if (params[:action] == 'index' || params[:action] == 'search') %>
    <h3 style="font-size:20px;"><%= link_to item.title, item %></h3>
  <% else %>
    <h3>
      <% if (params[:action] != 'show') %>
        <%= link_to item.title, item %>
      <% else %>
        <%= item.title%>
      <% end %>
    </h3>

  <% end %>

  <% if (params[:action] == 'show') %>
    <hr />
    <p><%= item.description %></p>
  <% else %>
    <p>Price: <%= number_to_currency item.price / 1.0 %></p>
  <% end %>

  <% if (params[:action] != 'show') %>
    <% if cart.include?(item) %>
      <%= link_to "Remove From Cart", cart_path(item), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, item.id) %>
        <%= button_tag class: "btn btn-warning item-cart" do %>
          <i class="bi bi-cart2" style="font-size:30px;"></i>
        <% end %>
      <% end %>
    <% end %>
    <%= button_to item, method: :get, class: "btn btn-primary" do %>
      View Item
    <% end %>
  <% end %>
</aside>

app/views/items/_item_buy.html.erb
<div id="item-show-card" class="">
  <p><%= number_to_currency item.price / 1.0 %></p>

  <div id="product-details">
    <% if cart.include?(item) %>
      <%= link_to "Remove From Cart", cart_path(item), method: :delete, class: "btn btn-danger d-inline-block mb-5 float-end" %>
      <%= link_to "View Cart", cart_index_path, class: "btn btn-warning d-inline-block w-100 mb-2" %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, item.id) %>
        <%= hidden_field_tag(:title, item.title) %>
        <%= button_tag class: "btn btn-warning d-inline-block w-100 mb-2" do %>
          Add To Cart
        <% end %>
      <% end %>
    <% end %>
    <%= form_with url: cart_buy_path, method: :post do %>
      <%= hidden_field_tag(:id, item.id) %>
      <%= hidden_field_tag(:title, item.title) %>
      <%= button_tag class: "btn btn-primary d-inline-block w-100 mb-5" do %>
        Buy
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<section id="items" class="mb-5">
  <%= render @items %>
</section>
<% if (params[:controller] != 'categories') %>
  <%= paginate @items %>
<% end %>

app/views/items/search.html.erb
<div class="container" style="display:flex;flex-direction:column;justify-content:center;">
  <section id="items" >
    <%= render @items %>
  </section>
  <%= paginate @items %>
</div>

app/views/items/show.html.erb
<section class="container" style="display:flex;">
  <div class="col-8">
    <%= render @item %>
  </div>
  <div class="col-4">
    <%= render partial: 'item_buy', locals: { item: @item }%>
  </div>
</section>